config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/posts/:id/vote', to: 'posts#vote', as: 'vote_post'
  post '/comments/:id/vote', to: 'comments#vote', as: 'vote_comment'

  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :categories, only: [:show, :new, :create, :edit, :update]
  resources :users, except: :new


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create, :edit, :update, :destroy]
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :require_user, only: [:create, :vote]
  before_action :require_creator, only: [:edit, :update]

  def create
    @comment = @post.comments.new(comment_params)
    @comment.creator = current_user

    if @comment.save
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      @post.reload
      render 'posts/show'
    end
  end

  def edit

  end

  def update
    if @comment.update(comment_params)
      redirect_to @post, notice: 'Comment was updated!'
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to :back
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = @comment.votes.create(creator: current_user, vote: params[:vote])
    
    respond_to do |format|
      format.html {
        if !@vote.save
          flash[:error] = 'You can only vote once per entry'
        end
        redirect_to :back
      }
      format.js
    end

  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def require_creator
    if !creator?(@comment)
      flash[:error] = 'Must be the creator to do that.'
      redirect_to root_path
    end
  end
end

app/views/comments/_comment.html.erb
<% show_post ||= false %>
<div class="row-fluid">
  <div class='well well-small span12'>
    <% if creator?(comment) %>
      <div class="dropdown pull-right">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-chevron-down"></i></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
            <li><%= link_to "edit comment", edit_post_comment_path(comment.post, comment), "tabindex" => "-1" %></li>
            <li><%= link_to 'delete comment', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></li>  
        </ul>
      </div>
    <% end %>
    <%= render 'shared/vote', obj: comment %>
    <em>"<%= comment.body %>"</em>
    <% if show_post %>
      on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
    <br/>
    <span class="quiet">by</span> <%= link_to comment.creator.username, user_path(comment.creator) %>
    <small> at <%= display_datetime(comment.created_at) %></small>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<div class="row-fluid">
  <div class="span12">
    <%= render "shared/error", obj: @comment %>

    <%= form_for ([@post, @comment]) do |form| %>
      <div>
        <%= form.text_area :body %>
      </div>
      <div>
        <%= form.submit @comment.new_record? ? "Create comment" : "Update comment" %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<h4>Edit Comment</h4>
<%= render 'comments/comment_form' %>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $("#comment_<%=@comment.id%>_votes").html(<%=@comment.total_votes%>);
<% else %>
  alert("You can only vote on a comment once.");
<% end %>