config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/posts/:id/vote', to: 'posts#vote', as: 'vote_post'
  post '/comments/:id/vote', to: 'comments#vote', as: 'vote_comment'

  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :categories, only: [:show, :new, :create, :edit, :update]
  resources :users, except: :new


end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :categorizations, dependent: :destroy
  has_many :categories, :through => :categorizations

  validates :title, presence: true
  validates :url, presence: true

  sluggable_column :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :vote]
  before_action :require_user, only: [:new, :create, :vote]
  before_action :require_creator, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse.paginate(page: params[:page], per_page: 10)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user
    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'The post was succesfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to :back
  end

  def vote
    @vote = @post.votes.create(creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html {
        if !@vote.save
          flash[:error] = 'You can only vote once per entry'
        end
        redirect_to :back
      }
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, :category_ids => [])
  end

  def require_creator
    if !creator?(@post)
      flash[:error] = 'Must be the creator to do that.'
      redirect_to root_path
    end
  end
end

app/views/posts/_form.html.erb
<%= render "shared/error", obj: @post %>

<%= form_for(@post) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :url %>
    <%= form.text_field :url%>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </div>
  <div>
  <%= form.submit "Save" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="fluid-row">
  <div class="well well-small span12">    
    <% if creator?(post) %>
      <div class="dropdown pull-right">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-chevron-down"></i></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
            <li><%= link_to "edit post", edit_post_path(post), "tabindex" => "-1" %></li>
            <li><%= link_to 'delete post', post, method: :delete, data: { confirm: 'Are you sure?' } %></li>  
        </ul>
      </div>
    <% end %>
    <%= render 'shared/vote', obj: post %>
    <div class="span6">
      <p><%= link_to post.title, url_with_protocol(post.url) %></p>
      <p>
        <span class="quiet">posted by</span> <%= link_to post.creator.username, user_path(post.creator) %>
        <small> at <%= display_datetime(post.created_at) %></small>
      </p>
      <ul class="nav post-nav">
        <li><small><span><%= link_to pluralize(post.comments.count, "comment"), post %></span></small></li>
        <li><%= render post.categories %></li>
      </ul>
    </div> 
  </div>
</div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="fluid-row">
  <%= render 'shared/content_title', title: 'All Posts' %>
</div>
<div class="fluid-row">
  <div class="span10">
    <% @posts.each do |post| %>
      <%= render 'post', post: post %>
    <% end %>
    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/posts/new.html.erb
<h2>New Post</h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="row-fluid">
  <% header = (link_to("All Posts", posts_path) + " &raquo; #{@post.title}".html_safe)%>
  <%= render 'shared/content_title', title: header %>
</div>

<div class="row-fluid">
  <div class="span10">
    <%= render 'post', post: @post %>
  </div>
</div>

<div class="row-fluid">
  <div class="span9">
    <h4><%= "Comment".pluralize(@post.comments.count) %>:</h4>
    <hr/>
    <% if logged_in? %>
      <%= render 'comments/comment_form' %>
    <% end %>
    <div class="row-fluid">
      <div class="span11">
        <% @comments.each do |comment| %>
          <%= render 'comments/comment', comment: comment %>
        <% end %>  
        <%= will_paginate @comments, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%=@post.id%>_votes").html(<%=@post.total_votes%>);
<% else %>
  alert("You can only vote on a post once.");
<% end %>