config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/posts/:id/vote', to: 'posts#vote', as: 'vote_post'
  post '/comments/:id/vote', to: 'comments#vote', as: 'vote_comment'

  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :categories, only: [:show, :new, :create, :edit, :update]
  resources :users, except: :new


end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>

<!-- Be sure to leave the brand out there if you want it shown -->
<%= link_to "Postit!", root_path, :class => 'brand' %>

<!-- Everything you want hidden at 940px or less, place within here -->
<div class="nav-collapse collapse">
  <!-- .nav, .navbar-search, .navbar-form, etc -->

  <ul class="nav">
    <li class='dropdown'>
      <%= link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do %>
        Categories <span class='caret'></span>
      <% end %>
      <ul class="dropdown-menu">
        <% categories.each do |category| %>
          <li><%= link_to category.name , category_path(category) %></li>
        <% end %>
        <% if admin? %>
          <li class='divider'></li>
          <li>
            <%= link_to(new_category_path) do %>
            <i class="icon-plus"></i>
            New Cetegory
            <% end %>
          </li>
        <% end %>
      </ul>
    </li>
    <% if logged_in? %>
      <li>
        <%= link_to "New post", new_post_path %>
      </li>
      <li class='dropdown'>
        <%= link_to('#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown') do %>
          <%= current_user.username %>
          <span class='caret'></span>
        <% end %>
        <ul class='dropdown-menu'>
          <% if admin? %>
            <li>
              <%= link_to(edit_user_path(current_user)) do %>
                <i class='icon-pencil'></i>
                edit profile
              <% end %>
            </li>
          <% end %>
          <li>
            <%= link_to(user_path(current_user)) do %>
              <i class='icon-user'></i>
              view profile
            <% end %>
          </li>
          <li>
            <%= link_to(logout_path) do %>
              <i class='icon-circle-arrow-left'></i>
              logout
            <% end %>
          </li>
          <li>
            <%= link_to(users_path) do %>
              <i class='icon-cog'></i>
              all users
            <% end %>
          </li>
        </ul>
      </li>
    <% else %>
      <li>
        <%= link_to 'Register', register_path %>
      </li>
      <li>
        <%= link_to 'Login', login_path %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>     
          </div>
        </div>
      </div>
    </nav>
    <div id="main" role="main">
      <div class="container-fluid">
         <div class="row-fluid">
            <div class="span10 offset1">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        <footer>
        </footer>
      </div> <!--! end of .container-fluid -->
    </div> <!--! end of #main -->
  </body>
</html>